import {
  Ampersand,
  Angry,
  Apple,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightLeft,
  Backpack,
  Ban,
  Bath,
  Bed,
  Bell,
  Bike,
  Bird,
  Blocks,
  Book,
  BookMarked,
  BookOpen,
  Bug,
  Bus,
  Car,
  Cat,
  Check,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleSlash,
  ClipboardList,
  Clock,
  Clock3,
  CloudRain,
  CloudSun,
  Coffee,
  CookingPot,
  Contact,
  Cookie,
  Copy,
  CornerDownRight,
  Croissant,
  CupSoda,
  Candy,
  Dice5,
  Dog,
  DoorClosed,
  Droplets,
  Ear,
  Egg,
  Eye,
  EyeOff,
  Flame,
  Flower2,
  Footprints,
  Frown,
  Ghost,
  Gamepad2,
  GlassWater,
  GraduationCap,
  Hand,
  Handshake,
  Heart,
  HeartCrack,
  HeartOff,
  HelpCircle,
  Hourglass,
  House,
  IceCreamBowl,
  Laugh,
  Leaf,
  LifeBuoy,
  Link,
  ListChecks,
  MapPin,
  Maximize,
  Medal,
  MessageCircleQuestion,
  Mic,
  Milk,
  Minimize,
  Monitor,
  Moon,
  MousePointer,
  Music,
  NotebookPen,
  Octagon,
  Palette,
  PartyPopper,
  Pause,
  PawPrint,
  Pencil,
  Pizza,
  Plus,
  Pointer,
  Puzzle,
  Rabbit,
  RefreshCw,
  Repeat,
  RotateCw,
  Salad,
  Scale,
  ScanFace,
  School,
  Scissors,
  Sandwich,
  Shuffle,
  ShowerHead,
  Slash,
  Smile,
  Snowflake,
  Sofa,
  Sparkle,
  Sparkles,
  Star,
  Sun,
  ThumbsDown,
  ThumbsUp,
  Timer,
  ToyBrick,
  TrainFront,
  TreePine,
  Trees,
  User,
  UserCog,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Volume1,
  Volume2,
  VolumeX,
  WashingMachine,
  Wheat,
  Wind,
  type LucideIcon,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  ampersand: Ampersand,
  angry: Angry,
  apple: Apple,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-right-left': ArrowRightLeft,
  backpack: Backpack,
  ban: Ban,
  bath: Bath,
  bed: Bed,
  bell: Bell,
  bike: Bike,
  bird: Bird,
  blocks: Blocks,
  book: Book,
  'book-marked': BookMarked,
  'book-open': BookOpen,
  bug: Bug,
  bus: Bus,
  candy: Candy,
  car: Car,
  cat: Cat,
  check: Check,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dot': CircleDot,
  'circle-help': CircleHelp,
  'circle-slash': CircleSlash,
  'clipboard-list': ClipboardList,
  clock: Clock,
  'clock-3': Clock3,
  'cloud-rain': CloudRain,
  'cloud-sun': CloudSun,
  coffee: Coffee,
  'cooking-pot': CookingPot,
  contact: Contact,
  cookie: Cookie,
  copy: Copy,
  'corner-down-right': CornerDownRight,
  croissant: Croissant,
  'cup-soda': CupSoda,
  'dice-5': Dice5,
  dog: Dog,
  'door-closed': DoorClosed,
  droplets: Droplets,
  ear: Ear,
  egg: Egg,
  eye: Eye,
  'eye-off': EyeOff,
  flame: Flame,
  'flower-2': Flower2,
  footprints: Footprints,
  frown: Frown,
  'gamepad-2': Gamepad2,
  ghost: Ghost,
  'glass-water': GlassWater,
  'graduation-cap': GraduationCap,
  hand: Hand,
  handshake: Handshake,
  heart: Heart,
  'heart-crack': HeartCrack,
  'heart-off': HeartOff,
  'help-circle': HelpCircle,
  hourglass: Hourglass,
  house: House,
  'ice-cream-bowl': IceCreamBowl,
  laugh: Laugh,
  leaf: Leaf,
  lifebuoy: LifeBuoy,
  link: Link,
  'list-checks': ListChecks,
  'map-pin': MapPin,
  maximize: Maximize,
  medal: Medal,
  'message-circle-question': MessageCircleQuestion,
  mic: Mic,
  milk: Milk,
  minimize: Minimize,
  monitor: Monitor,
  moon: Moon,
  'mouse-pointer': MousePointer,
  music: Music,
  'notebook-pen': NotebookPen,
  octagon: Octagon,
  palette: Palette,
  'party-popper': PartyPopper,
  pause: Pause,
  'paw-print': PawPrint,
  pencil: Pencil,
  pizza: Pizza,
  plus: Plus,
  pointer: Pointer,
  puzzle: Puzzle,
  rabbit: Rabbit,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  'rotate-cw': RotateCw,
  salad: Salad,
  scale: Scale,
  'scan-face': ScanFace,
  school: School,
  sandwich: Sandwich,
  scissors: Scissors,
  shuffle: Shuffle,
  'shower-head': ShowerHead,
  slash: Slash,
  smile: Smile,
  snowflake: Snowflake,
  sofa: Sofa,
  sparkle: Sparkle,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  timer: Timer,
  'toy-brick': ToyBrick,
  'train-front': TrainFront,
  'tree-pine': TreePine,
  trees: Trees,
  user: User,
  'user-cog': UserCog,
  'user-plus': UserPlus,
  'user-round': UserRound,
  users: Users,
  'users-round': UsersRound,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'washing-machine': WashingMachine,
  wheat: Wheat,
  wind: Wind,
}

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? Circle
}

/** Explicit allowlist of every icon id this build can render. */
export function isKnownIconId(name: unknown): name is string {
  return typeof name === 'string' && Object.prototype.hasOwnProperty.call(ICONS, name)
}
