import { PROTECTED_CORE_ENTRIES } from './protected-core'
import type { VocabEntry } from './types'

const FRINGE: VocabEntry[] = [
  {
    id: 'i',
    label: 'I',
    category: 'people',
    icon: 'user',
    functions: ['comment', 'request', 'feeling'],
    complexity: 'early',
  },
  {
    id: 'you',
    label: 'You',
    category: 'people',
    icon: 'user-round',
    functions: ['people', 'ask'],
    complexity: 'early',
  },
  {
    id: 'we',
    label: 'We',
    category: 'people',
    icon: 'users',
    functions: ['people', 'comment'],
    complexity: 'mid',
  },
  {
    id: 'want',
    label: 'Want',
    category: 'core',
    icon: 'hand',
    functions: ['request'],
    complexity: 'early',
  },
  {
    id: 'need',
    label: 'Need',
    category: 'core',
    icon: 'circle-alert',
    functions: ['request'],
    complexity: 'mid',
  },
  {
    id: 'like',
    label: 'Like',
    category: 'core',
    icon: 'heart',
    functions: ['comment', 'feeling'],
    complexity: 'early',
  },
  {
    id: 'dont-like',
    label: "Don't like",
    category: 'core',
    icon: 'heart-off',
    functions: ['reject', 'comment'],
    complexity: 'early',
  },
  {
    id: 'feel',
    label: 'Feel',
    category: 'feeling',
    icon: 'smile',
    functions: ['feeling'],
    complexity: 'early',
  },
  {
    id: 'go',
    label: 'Go',
    category: 'action',
    icon: 'arrow-right',
    functions: ['action', 'request'],
    complexity: 'early',
  },
  {
    id: 'look',
    label: 'Look',
    category: 'action',
    icon: 'eye',
    functions: ['action', 'comment'],
    complexity: 'early',
  },
  {
    id: 'that',
    label: 'That',
    category: 'core',
    icon: 'pointer',
    functions: ['comment', 'request'],
    complexity: 'early',
  },
  {
    id: 'this',
    label: 'This',
    category: 'core',
    icon: 'mouse-pointer',
    functions: ['comment', 'request'],
    complexity: 'early',
  },
  {
    id: 'please',
    label: 'Please',
    category: 'core',
    icon: 'sparkle',
    functions: ['request'],
    complexity: 'early',
  },
  {
    id: 'thanks',
    label: 'Thanks',
    category: 'core',
    icon: 'handshake',
    functions: ['comment'],
    complexity: 'early',
  },
  {
    id: 'what',
    label: 'What',
    category: 'ask',
    icon: 'help-circle',
    functions: ['ask'],
    complexity: 'early',
  },
  {
    id: 'where',
    label: 'Where',
    category: 'ask',
    icon: 'map-pin',
    functions: ['ask'],
    complexity: 'early',
  },
  {
    id: 'who',
    label: 'Who',
    category: 'ask',
    icon: 'contact',
    functions: ['ask'],
    complexity: 'mid',
  },
  {
    id: 'why',
    label: 'Why',
    category: 'ask',
    icon: 'message-circle-question',
    functions: ['ask'],
    complexity: 'mid',
  },
  {
    id: 'when',
    label: 'When',
    category: 'ask',
    icon: 'clock',
    functions: ['ask'],
    complexity: 'later',
  },
  {
    id: 'can',
    label: 'Can',
    category: 'ask',
    icon: 'circle-help',
    functions: ['ask', 'request'],
    complexity: 'mid',
  },
  {
    id: 'and',
    label: 'And',
    category: 'core',
    icon: 'ampersand',
    functions: ['comment'],
    complexity: 'mid',
  },
  {
    id: 'to',
    label: 'To',
    category: 'core',
    icon: 'corner-down-right',
    functions: ['action'],
    complexity: 'early',
  },
  {
    id: 'not',
    label: 'Not',
    category: 'core',
    icon: 'slash',
    functions: ['reject'],
    complexity: 'mid',
  },
  {
    id: 'wait',
    label: 'Wait',
    category: 'action',
    icon: 'hourglass',
    functions: ['request', 'repair'],
    complexity: 'early',
  },
  {
    id: 'again',
    label: 'Again',
    category: 'core',
    icon: 'rotate-cw',
    functions: ['request', 'repair'],
    complexity: 'early',
  },
  {
    id: 'different',
    label: 'Different',
    category: 'describe',
    icon: 'shuffle',
    functions: ['repair', 'comment'],
    complexity: 'mid',
  },
  {
    id: 'same',
    label: 'Same',
    category: 'describe',
    icon: 'copy',
    functions: ['comment'],
    complexity: 'mid',
  },
  {
    id: 'try',
    label: 'Try again',
    category: 'core',
    icon: 'refresh-cw',
    functions: ['repair'],
    complexity: 'mid',
  },
  {
    id: 'say-again',
    label: 'Say again',
    category: 'core',
    icon: 'repeat',
    functions: ['repair', 'ask'],
    complexity: 'mid',
  },
  {
    id: 'happy',
    label: 'Happy',
    category: 'feeling',
    icon: 'laugh',
    functions: ['feeling'],
    complexity: 'early',
  },
  {
    id: 'sad',
    label: 'Sad',
    category: 'feeling',
    icon: 'frown',
    functions: ['feeling'],
    complexity: 'early',
  },
  {
    id: 'angry',
    label: 'Angry',
    category: 'feeling',
    icon: 'angry',
    functions: ['feeling'],
    complexity: 'early',
  },
  {
    id: 'worried',
    label: 'Worried',
    category: 'feeling',
    icon: 'cloud-rain',
    functions: ['feeling'],
    complexity: 'mid',
  },
  {
    id: 'tired',
    label: 'Tired',
    category: 'feeling',
    icon: 'moon',
    functions: ['feeling', 'body'],
    complexity: 'early',
  },
  {
    id: 'scared',
    label: 'Scared',
    category: 'feeling',
    icon: 'ghost',
    functions: ['feeling'],
    complexity: 'early',
  },
  {
    id: 'calm',
    label: 'Calm',
    category: 'feeling',
    icon: 'leaf',
    functions: ['feeling'],
    complexity: 'mid',
  },
  {
    id: 'confused',
    label: 'Confused',
    category: 'feeling',
    icon: 'help-circle',
    functions: ['feeling', 'repair'],
    complexity: 'later',
  },
  {
    id: 'proud',
    label: 'Proud',
    category: 'feeling',
    icon: 'star',
    functions: ['feeling', 'comment'],
    complexity: 'later',
  },
  {
    id: 'unfair',
    label: 'Unfair',
    category: 'feeling',
    icon: 'scale',
    functions: ['comment', 'reject'],
    complexity: 'later',
  },
  {
    id: 'head',
    label: 'Head',
    category: 'body',
    icon: 'scan-face',
    functions: ['body'],
    complexity: 'early',
  },
  {
    id: 'tummy',
    label: 'Tummy',
    category: 'body',
    icon: 'circle',
    functions: ['body'],
    complexity: 'early',
  },
  {
    id: 'ear',
    label: 'Ear',
    category: 'body',
    icon: 'ear',
    functions: ['body'],
    complexity: 'early',
  },
  {
    id: 'too-loud',
    label: 'Too loud',
    category: 'body',
    icon: 'volume-x',
    functions: ['body', 'reject'],
    complexity: 'mid',
  },
  {
    id: 'too-bright',
    label: 'Too bright',
    category: 'body',
    icon: 'sun',
    functions: ['body', 'reject'],
    complexity: 'mid',
  },
  {
    id: 'hot',
    label: 'Hot',
    category: 'body',
    icon: 'flame',
    functions: ['body', 'describe'],
    complexity: 'early',
  },
  {
    id: 'cold',
    label: 'Cold',
    category: 'body',
    icon: 'snowflake',
    functions: ['body', 'describe'],
    complexity: 'early',
  },
  {
    id: 'friend',
    label: 'Friend',
    category: 'people',
    icon: 'user-plus',
    functions: ['people'],
    complexity: 'early',
    routines: ['play', 'school'],
  },
  {
    id: 'family',
    label: 'Family',
    category: 'people',
    icon: 'users-round',
    functions: ['people'],
    complexity: 'early',
    routines: ['home'],
  },
  {
    id: 'teacher',
    label: 'Teacher',
    category: 'people',
    icon: 'graduation-cap',
    functions: ['people'],
    complexity: 'mid',
    routines: ['school'],
  },
  {
    id: 'grown-up',
    label: 'Grown-up',
    category: 'people',
    icon: 'user-cog',
    functions: ['people'],
    complexity: 'mid',
  },
  {
    id: 'privacy',
    label: 'Privacy',
    category: 'people',
    icon: 'door-closed',
    functions: ['request', 'reject'],
    complexity: 'later',
  },
  {
    id: 'choice',
    label: 'Choice',
    category: 'core',
    icon: 'list-checks',
    functions: ['request', 'ask'],
    complexity: 'later',
  },
  {
    id: 'explain',
    label: 'Explain',
    category: 'ask',
    icon: 'book-open',
    functions: ['ask', 'repair'],
    complexity: 'later',
  },
  {
    id: 'because',
    label: 'Because',
    category: 'core',
    icon: 'link',
    functions: ['comment'],
    complexity: 'later',
  },
  {
    id: 'later',
    label: 'Later',
    category: 'core',
    icon: 'timer',
    functions: ['request', 'comment'],
    complexity: 'later',
  },
  {
    id: 'home',
    label: 'Home',
    category: 'place',
    icon: 'house',
    functions: ['place'],
    complexity: 'early',
    routines: ['home'],
  },
  {
    id: 'school',
    label: 'School',
    category: 'place',
    icon: 'school',
    functions: ['place'],
    complexity: 'early',
    routines: ['school'],
  },
  {
    id: 'outside',
    label: 'Outside',
    category: 'place',
    icon: 'trees',
    functions: ['place'],
    complexity: 'early',
    routines: ['outside', 'play'],
  },
  {
    id: 'toilet',
    label: 'Toilet',
    category: 'place',
    icon: 'bath',
    functions: ['place', 'request'],
    complexity: 'early',
    routines: ['home', 'school'],
  },
  {
    id: 'play',
    label: 'Play',
    category: 'action',
    icon: 'puzzle',
    functions: ['action', 'request'],
    complexity: 'early',
    routines: ['play'],
  },
  {
    id: 'game',
    label: 'Game',
    category: 'routine',
    icon: 'dice-5',
    functions: ['request'],
    complexity: 'early',
    routines: ['play'],
  },
  {
    id: 'toy',
    label: 'Toy',
    category: 'routine',
    icon: 'toy-brick',
    functions: ['request'],
    complexity: 'early',
    routines: ['play'],
  },
  {
    id: 'turn',
    label: 'My turn',
    category: 'action',
    icon: 'arrow-left-right',
    functions: ['request', 'comment'],
    complexity: 'mid',
    routines: ['play', 'school'],
  },
  {
    id: 'your-turn',
    label: 'Your turn',
    category: 'action',
    icon: 'arrow-right-left',
    functions: ['comment'],
    complexity: 'mid',
    routines: ['play', 'school'],
  },
  {
    id: 'eat',
    label: 'Eat',
    category: 'action',
    icon: 'utensils',
    functions: ['action', 'request'],
    complexity: 'early',
    routines: ['food'],
  },
  {
    id: 'drink',
    label: 'Drink',
    category: 'action',
    icon: 'cup-soda',
    functions: ['action', 'request'],
    complexity: 'early',
    routines: ['food'],
  },
  {
    id: 'hungry',
    label: 'Hungry',
    category: 'body',
    icon: 'salad',
    functions: ['body', 'request'],
    complexity: 'early',
    routines: ['food'],
  },
  {
    id: 'thirsty',
    label: 'Thirsty',
    category: 'body',
    icon: 'glass-water',
    functions: ['body', 'request'],
    complexity: 'early',
    routines: ['food'],
  },
  {
    id: 'snack',
    label: 'Snack',
    category: 'routine',
    icon: 'cookie',
    functions: ['request'],
    complexity: 'early',
    routines: ['food'],
  },
  {
    id: 'water',
    label: 'Water',
    category: 'routine',
    icon: 'droplets',
    functions: ['request'],
    complexity: 'early',
    routines: ['food'],
  },
  {
    id: 'tastes',
    label: 'Tastes',
    category: 'describe',
    icon: 'utensils-crossed',
    functions: ['comment'],
    complexity: 'mid',
    routines: ['food'],
  },
  {
    id: 'work',
    label: 'Work',
    category: 'action',
    icon: 'clipboard-list',
    functions: ['action'],
    complexity: 'mid',
    routines: ['school'],
  },
  {
    id: 'read',
    label: 'Read',
    category: 'action',
    icon: 'book',
    functions: ['action', 'request'],
    complexity: 'early',
    routines: ['school', 'home'],
    interests: ['stories'],
  },
  {
    id: 'write',
    label: 'Write',
    category: 'action',
    icon: 'pencil',
    functions: ['action'],
    complexity: 'mid',
    routines: ['school'],
  },
  {
    id: 'break-time',
    label: 'Break time',
    category: 'routine',
    icon: 'coffee',
    functions: ['request', 'place'],
    complexity: 'mid',
    routines: ['school'],
  },
  {
    id: 'quiet',
    label: 'Quiet',
    category: 'describe',
    icon: 'volume-1',
    functions: ['request', 'comment'],
    complexity: 'mid',
    routines: ['home', 'school'],
  },
  {
    id: 'bed',
    label: 'Bed',
    category: 'place',
    icon: 'bed',
    functions: ['place', 'request'],
    complexity: 'early',
    routines: ['home'],
  },
  {
    id: 'tv',
    label: 'Screen',
    category: 'routine',
    icon: 'monitor',
    functions: ['request'],
    complexity: 'mid',
    routines: ['home'],
  },
  {
    id: 'park',
    label: 'Park',
    category: 'place',
    icon: 'tree-pine',
    functions: ['place'],
    complexity: 'early',
    routines: ['outside'],
  },
  {
    id: 'walk',
    label: 'Walk',
    category: 'action',
    icon: 'footprints',
    functions: ['action', 'request'],
    complexity: 'early',
    routines: ['outside'],
  },
  {
    id: 'weather',
    label: 'Weather',
    category: 'describe',
    icon: 'cloud-sun',
    functions: ['comment'],
    complexity: 'mid',
    routines: ['outside'],
  },
  {
    id: 'animal',
    label: 'Animal',
    category: 'routine',
    icon: 'paw-print',
    functions: ['comment', 'request'],
    complexity: 'early',
    interests: ['animals'],
    routines: ['outside'],
  },
  {
    id: 'dog',
    label: 'Dog',
    category: 'routine',
    icon: 'dog',
    functions: ['comment', 'request'],
    complexity: 'early',
    interests: ['animals'],
  },
  {
    id: 'cat',
    label: 'Cat',
    category: 'routine',
    icon: 'cat',
    functions: ['comment', 'request'],
    complexity: 'early',
    interests: ['animals'],
  },
  {
    id: 'car',
    label: 'Car',
    category: 'routine',
    icon: 'car',
    functions: ['comment', 'request'],
    complexity: 'early',
    interests: ['vehicles'],
  },
  {
    id: 'bus',
    label: 'Bus',
    category: 'routine',
    icon: 'bus',
    functions: ['comment', 'place'],
    complexity: 'early',
    interests: ['vehicles'],
    routines: ['outside'],
  },
  {
    id: 'train',
    label: 'Train',
    category: 'routine',
    icon: 'train-front',
    functions: ['comment', 'request'],
    complexity: 'early',
    interests: ['vehicles'],
  },
  {
    id: 'music',
    label: 'Music',
    category: 'routine',
    icon: 'music',
    functions: ['request', 'comment'],
    complexity: 'early',
    interests: ['music'],
  },
  {
    id: 'sing',
    label: 'Sing',
    category: 'action',
    icon: 'mic',
    functions: ['action', 'request'],
    complexity: 'early',
    interests: ['music'],
  },
  {
    id: 'sport',
    label: 'Sport',
    category: 'routine',
    icon: 'medal',
    functions: ['request', 'comment'],
    complexity: 'mid',
    interests: ['sport'],
  },
  {
    id: 'ball',
    label: 'Ball',
    category: 'routine',
    icon: 'circle-dot',
    functions: ['request'],
    complexity: 'early',
    interests: ['sport'],
    routines: ['play', 'outside'],
  },
  {
    id: 'draw',
    label: 'Draw',
    category: 'action',
    icon: 'palette',
    functions: ['action', 'request'],
    complexity: 'early',
    interests: ['art'],
  },
  {
    id: 'colour',
    label: 'Colour',
    category: 'describe',
    icon: 'paintbrush',
    functions: ['describe', 'comment'],
    complexity: 'early',
    interests: ['art'],
  },
  {
    id: 'story',
    label: 'Story',
    category: 'routine',
    icon: 'book-marked',
    functions: ['request', 'comment'],
    complexity: 'early',
    interests: ['stories'],
  },
  {
    id: 'garden',
    label: 'Garden',
    category: 'place',
    icon: 'flower-2',
    functions: ['place'],
    complexity: 'early',
    interests: ['outdoors'],
    routines: ['outside', 'home'],
  },
  {
    id: 'bike',
    label: 'Bike',
    category: 'routine',
    icon: 'bike',
    functions: ['request', 'action'],
    complexity: 'early',
    interests: ['outdoors', 'vehicles'],
    routines: ['outside', 'play'],
  },
  {
    id: 'fruit',
    label: 'Fruit',
    category: 'routine',
    icon: 'apple',
    functions: ['request'],
    complexity: 'early',
    interests: ['food'],
    routines: ['food'],
  },
  {
    id: 'fun',
    label: 'Fun',
    category: 'describe',
    icon: 'party-popper',
    functions: ['comment', 'feeling'],
    complexity: 'early',
    routines: ['play'],
  },
  {
    id: 'blocks',
    label: 'Blocks',
    category: 'routine',
    icon: 'blocks',
    functions: ['request', 'comment'],
    complexity: 'early',
    routines: ['play'],
  },
  {
    id: 'hide-seek',
    label: 'Hide and seek',
    category: 'routine',
    icon: 'eye-off',
    functions: ['request'],
    complexity: 'early',
    routines: ['play'],
  },
  {
    id: 'video-game',
    label: 'Video game',
    category: 'routine',
    icon: 'gamepad-2',
    functions: ['request'],
    complexity: 'mid',
    routines: ['play'],
  },
  {
    id: 'egg',
    label: 'Egg',
    category: 'routine',
    icon: 'egg',
    functions: ['request'],
    complexity: 'early',
    routines: ['food'],
  },
  {
    id: 'milk',
    label: 'Milk',
    category: 'routine',
    icon: 'milk',
    functions: ['request'],
    complexity: 'early',
    routines: ['food'],
  },
  {
    id: 'sweet',
    label: 'Sweets',
    category: 'routine',
    icon: 'candy',
    functions: ['request'],
    complexity: 'early',
    routines: ['food'],
  },
  {
    id: 'ice-cream',
    label: 'Ice cream',
    category: 'routine',
    icon: 'ice-cream-bowl',
    functions: ['request'],
    complexity: 'early',
    routines: ['food'],
  },
  {
    id: 'pizza',
    label: 'Pizza',
    category: 'routine',
    icon: 'pizza',
    functions: ['request'],
    complexity: 'early',
    routines: ['food'],
  },
  {
    id: 'dinner',
    label: 'Dinner',
    category: 'routine',
    icon: 'cooking-pot',
    functions: ['request'],
    complexity: 'early',
    routines: ['home', 'food'],
  },
  {
    id: 'backpack',
    label: 'Backpack',
    category: 'routine',
    icon: 'backpack',
    functions: ['comment', 'request'],
    complexity: 'early',
    routines: ['school'],
  },
  {
    id: 'bell',
    label: 'Bell',
    category: 'routine',
    icon: 'bell',
    functions: ['comment'],
    complexity: 'mid',
    routines: ['school'],
  },
  {
    id: 'notebook',
    label: 'Notebook',
    category: 'routine',
    icon: 'notebook-pen',
    functions: ['request', 'comment'],
    complexity: 'mid',
    routines: ['school'],
  },
  {
    id: 'craft',
    label: 'Craft',
    category: 'routine',
    icon: 'scissors',
    functions: ['request', 'action'],
    complexity: 'mid',
    routines: ['school'],
  },
  {
    id: 'sofa',
    label: 'Sofa',
    category: 'place',
    icon: 'sofa',
    functions: ['place', 'request'],
    complexity: 'early',
    routines: ['home'],
  },
  {
    id: 'wash',
    label: 'Wash',
    category: 'action',
    icon: 'washing-machine',
    functions: ['action', 'request'],
    complexity: 'mid',
    routines: ['home'],
  },
  {
    id: 'shower',
    label: 'Shower',
    category: 'place',
    icon: 'shower-head',
    functions: ['place', 'request'],
    complexity: 'mid',
    routines: ['home'],
  },
  {
    id: 'sunny',
    label: 'Sunny',
    category: 'describe',
    icon: 'sun',
    functions: ['comment'],
    complexity: 'early',
    routines: ['outside'],
  },
  {
    id: 'rain',
    label: 'Rain',
    category: 'describe',
    icon: 'cloud-rain',
    functions: ['comment'],
    complexity: 'early',
    routines: ['outside'],
  },
  {
    id: 'windy',
    label: 'Windy',
    category: 'describe',
    icon: 'wind',
    functions: ['comment'],
    complexity: 'early',
    routines: ['outside'],
  },
  {
    id: 'bird',
    label: 'Bird',
    category: 'routine',
    icon: 'bird',
    functions: ['comment', 'request'],
    complexity: 'early',
    routines: ['outside'],
  },
  {
    id: 'rabbit',
    label: 'Rabbit',
    category: 'routine',
    icon: 'rabbit',
    functions: ['comment', 'request'],
    complexity: 'early',
    interests: ['animals', 'outdoors'],
    routines: ['outside'],
  },
  {
    id: 'big',
    label: 'Big',
    category: 'describe',
    icon: 'maximize',
    functions: ['comment'],
    complexity: 'early',
  },
  {
    id: 'little',
    label: 'Little',
    category: 'describe',
    icon: 'minimize',
    functions: ['comment'],
    complexity: 'early',
  },
  {
    id: 'good',
    label: 'Good',
    category: 'describe',
    icon: 'thumbs-up',
    functions: ['comment'],
    complexity: 'early',
  },
  {
    id: 'bad',
    label: 'Bad',
    category: 'describe',
    icon: 'thumbs-down',
    functions: ['comment', 'reject'],
    complexity: 'early',
  },
  {
    id: 'fun',
    label: 'Fun',
    category: 'describe',
    icon: 'party-popper',
    functions: ['comment', 'feeling'],
    complexity: 'early',
  },
  {
    id: 'boring',
    label: 'Boring',
    category: 'describe',
    icon: 'clock-3',
    functions: ['comment'],
    complexity: 'later',
  },
]

export const VOCABULARY: readonly VocabEntry[] = [...PROTECTED_CORE_ENTRIES, ...FRINGE]

const BY_ID = new Map(VOCABULARY.map((entry) => [entry.id, entry]))

export function getVocabById(id: string): VocabEntry | undefined {
  const entry = BY_ID.get(id)
  return entry ? { ...entry } : undefined
}

export function getVocabLabel(id: string): string | undefined {
  return BY_ID.get(id)?.label
}

export function getAllVocabIds(): string[] {
  return VOCABULARY.map((entry) => entry.id)
}

export function getAllowlistedIds(): ReadonlySet<string> {
  return new Set(VOCABULARY.map((entry) => entry.id))
}

export function getModelAllowlist(): ReadonlySet<string> {
  return new Set(FRINGE.map((entry) => entry.id))
}
